weibo:
  client:
    clientId: 644336069
    clientSecret: be57719150f4085a92120bd2f012861a
github:
  client:
    clientId: 4b7c4d8da7668e66b851
    clientSecret: cff6aeb515ddffdd1ad411a21c2a4a4d7fa2453d
facebook:
  client:
    clientId: 295460234539472
    clientSecret: 27d0b5a09a668c8578293559f770bea1

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    root: debug