github:
  client:
    clientId: 4b7c4d8da7668e66b851
    clientSecret: cff6aeb515ddffdd1ad411a21c2a4a4d7fa2453d

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

logging:
  level:
    root: debug